GET http://localhost:1234/movies

###
GET http://localhost:1234/movies/5ad1a235-0d9c-410a-b32b-220d91689a08

###
POST  http://localhost:1234/movies
Content-Type: application/json

{
  "id": "5ad1a235-0d9c-410a-b32b-220d91689a08",
  "title": "Inception",
  "year": 2010,
  "director": "Christopher Nolan",
  "duration": 148,
  "poster": "https://m.media-amazon.com/images/I/91Rc8cAmnAL._AC_UF1000,1000_QL80_.jpg",
  "genre": [
    "Action",
    "Adventure",
    "Sci-Fi"
  ],
  "rate": 8.8,
  "salchicon": 123
}